spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_club
    username: root
    password: your_mysql_password_here  # 请修改为你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

# 如需修改端口，取消注释下面两行
#server:
#  port: 8888

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo 